In [1]:
! pip install seaborn

In [1]:
 # Libs principais
from model import *
import pandas as pd
# Controle de execução e pastas
import os
# Desativar alguns warnings
import warnings
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt
plt.style.use('ggplot')

def VirtualLaneDetector(x,y,virtual_lane_lim,virtual_lane_width):
    virtual_lane = -1
    count = 0

    for list_point in virtual_lane_lim:
        count = count + 1
        func_virtual_lane = PolygonalToFunction(list_point)
        if (y>=func_virtual_lane(x)-0.5*virtual_lane_width) and (y<=func_virtual_lane(x)+0.5*virtual_lane_width):
            virtual_lane = count
            break

    return virtual_lane

In [2]:
os.chdir("data_ignore")

In [14]:
if __name__=="__main__":
    # os.chdir("data_ignore")
    root_file = "data/json"
    all_files = os.listdir(root_file)

    df = {"id_voo":[],"duracao":[],"veiculos":[],"faixas":[]}

    for f in all_files:
        try:
            model = YoloMicroscopicDataProcessing()
            model.ImportFromJSON(os.path.join(root_file,f))

            if "79" in f:
                model.df = model.df[model.df["traffic_lane"].isin([6,7,8,9,10,11])]
            if "10" in f:
                model.df = model.df[model.df["traffic_lane"].isin([2,3,4,5])]
            if "32" in f:
                model.df = model.df[model.df["traffic_lane"].isin([1,2,3,4])]

            df["id_voo"].append(f.split(".")[0])
            df["duracao"].append((model.df["frame"].max()-model.df["frame"].min())/(30*60))
            df["veiculos"].append(len(model.df["id"].unique()))
            df["faixas"].append(len(model.df["traffic_lane"].unique()))
        except Exception as e:
            print(f"Erro {f}")
            print(e)
    
    df = pd.DataFrame(df)

In [15]:
df

    id_voo    duracao  veiculos  faixas
0   10_A_1  13.812778       813       4
1   10_A_2   3.144444       151       4
2   10_A_3  13.833889       705       4
3   10_A_4   6.177222       338       4
4   10_A_5   7.011667       381       4
5   10_B_1  13.807778       577       4
6   10_B_2   6.197222       253       4
7   10_B_3  13.782222       585       4
8   10_B_4   5.106111       242       4
9   10_B_5   5.002778       251       4
10  32_A_1  13.833889       739       4
11  32_A_2   5.159444       285       4
12  32_A_3  13.833333       757       4
13  32_A_4   8.156111       449       4
14  32_A_5   3.466667       190       4
15  32_B_1  13.833889       748       4
16  32_B_2   4.151111       199       4
17  32_B_3  13.833333       714       4
18  32_B_4   6.152222       305       4
19  32_B_5   3.496667       187       4
20  79_A_1  13.835556      2010       6
21  79_A_2   5.133889       700       6
22  79_A_3  13.835556      1997       6
23  79_A_4   4.925000       746       6
24  79_A_5   5.004444       793       6
25  79_B_1  13.835556      2069       6
26  79_B_2   4.175000       622       6
27  79_B_3  13.835556      2018       6
28  79_B_4   4.310556       613       6
29  79_B_5  13.835556      1977       6
30  79_B_6   5.045556       728       6
31  79_B_7  13.835556      1933       6
32  79_B_8   4.101667       530       6

In [16]:
df.to_excel("duracao.xlsx")